spring:
  profiles:
    default: local
  application:
    name: bluedragon
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database?serverTimezone=Asia/Seoul;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /docs/swagger
    url: /docs/openapi3.yaml
    disable-swagger-default-url: true
    filter: true
    persist-authorization: true
    display-request-duration: true
