spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hackertonfive@gmail.com
    password: "nuthkbfljdgjfoxh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
